# TheTitanRain's Shadowrocket config rules.
# Direct Rules

DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT
DOMAIN-SUFFIX,apple.co,DIRECT
DOMAIN-SUFFIX,apple-dns.net,DIRECT

DOMAIN-SUFFIX,yandex.net,DIRECT

DOMAIN-SUFFIX,ozonusercontent.com,DIRECT
